# Generated by Django 5.0.8 on 2024-08-11 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 11, 16, 9, 51, 522721, tzinfo=datetime.timezone.utc)),
        ),
    ]
