# Generated by Django 5.0.8 on 2024-08-21 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_alter_article_pub_date_alter_article_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 21, 10, 10, 53, 232938, tzinfo=datetime.timezone.utc)),
        ),
    ]
