# Generated by Django 5.0.8 on 2024-08-21 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 21, 11, 10, 42, 701272, tzinfo=datetime.timezone.utc)),
        ),
    ]
