# Generated by Django 5.0.8 on 2024-08-21 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.DurationField(default=datetime.timedelta(days=23, seconds=78234)),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 21, 15, 53, 8, 565612, tzinfo=datetime.timezone.utc)),
        ),
    ]
