# Generated by Django 5.0.8 on 2024-08-21 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_is_published_alter_article_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 21, 16, 25, 23, 905629, tzinfo=datetime.timezone.utc)),
        ),
    ]
