# Generated by Django 5.0.8 on 2024-08-21 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_floatfield_article_myfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='myfile',
            field=models.FileField(null=True, upload_to='test'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 21, 16, 59, 5, 672283, tzinfo=datetime.timezone.utc)),
        ),
    ]
