# Generated by Django 5.0.8 on 2024-08-22 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_article_myfile_alter_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 22, 8, 37, 9, 473779, tzinfo=datetime.timezone.utc)),
        ),
    ]
