# Generated by Django 5.0.8 on 2024-08-24 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_article_status_alter_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 24, 11, 30, 18, 288036, tzinfo=datetime.timezone.utc)),
        ),
    ]
