# Generated by Django 5.0.8 on 2024-09-03 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_message_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 3, 10, 50, 36, 272948, tzinfo=datetime.timezone.utc)),
        ),
    ]
