# Generated by Django 5.0.8 on 2024-09-13 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_message_age_alter_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 3, 39, 16, 724725, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 13, 3, 39, 16, 722734, tzinfo=datetime.timezone.utc)),
        ),
    ]
