# Generated by Django 5.0.8 on 2024-09-13 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_message_date_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 6, 2, 4, 177832, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 6, 2, 4, 179826, tzinfo=datetime.timezone.utc)),
        ),
    ]
